
// Sample seller creation utility
export const sampleSellers = [
{
  business_name: "Mithila Heritage Foods",
  owner_name: "Rajesh Kumar Jha",
  description: "Traditional Mithila cuisine crafted with love and passed down through generations. We specialize in authentic Maithili delicacies made with organic ingredients sourced directly from local farms.",
  address: "Janakpur Road, Near Kamla Nehru Park",
  city: "Madhubani",
  state: "Bihar",
  email: "rajesh@mithilaheritage.com",
  phone: "+91-9876543210",
  profile_image: "",
  banner_image: "",
  rating: 4.8,
  total_reviews: 127,
  is_verified: true,
  established_year: 2015,
  specialties: "Litti Chokha, Tilkut, Khaja, Makhana"
},
{
  business_name: "Bihar Sweets Corner",
  owner_name: "Sunita Devi",
  description: "Home-made sweets and savories that capture the essence of Bihar's rich culinary heritage. Each product is made with traditional recipes and premium ingredients.",
  address: "Station Road, Near Bus Stand",
  city: "Patna",
  state: "Bihar",
  email: "sunita@biharsweets.com",
  phone: "+91-9876543211",
  profile_image: "",
  banner_image: "",
  rating: 4.6,
  total_reviews: 89,
  is_verified: true,
  established_year: 2018,
  specialties: "Sattu, Tilkut, Chana Ghugni, Kheer"
},
{
  business_name: "Janakpur Delicacies",
  owner_name: "Amit Kumar Singh",
  description: "Authentic flavors from the land of Sita Mata. We bring you traditional recipes that have been perfected over centuries, maintaining the original taste and nutritional value.",
  address: "Durga Mandir Complex, Main Market",
  city: "Sitamarhi",
  state: "Bihar",
  email: "amit@janakpurdelicacies.com",
  phone: "+91-9876543212",
  profile_image: "",
  banner_image: "",
  rating: 4.7,
  total_reviews: 156,
  is_verified: true,
  established_year: 2012,
  specialties: "Litti, Ghugni, Tilkut, Mithila Papad"
},
{
  business_name: "Darbhanga Royal Foods",
  owner_name: "Priya Kumari",
  description: "Royal recipes from the Darbhanga palace kitchens. Experience the taste of Mithila royalty with our carefully curated selection of traditional and fusion delicacies.",
  address: "Palace Road, Heritage Quarter",
  city: "Darbhanga",
  state: "Bihar",
  email: "priya@darbhangaroyal.com",
  phone: "+91-9876543213",
  profile_image: "",
  banner_image: "",
  rating: 4.9,
  total_reviews: 203,
  is_verified: true,
  established_year: 2010,
  specialties: "Royal Makhana, Khaja, Tilkut, Sattu Drink"
},
{
  business_name: "Mithila Mom's Kitchen",
  owner_name: "Kavita Jha",
  description: "Just like mom used to make! Our kitchen recreates the warmth and love of traditional Mithila home cooking with authentic recipes passed down through generations.",
  address: "Gandhi Chowk, Near School",
  city: "Samastipur",
  state: "Bihar",
  email: "kavita@mithilamoms.com",
  phone: "+91-9876543214",
  profile_image: "",
  banner_image: "",
  rating: 4.5,
  total_reviews: 78,
  is_verified: true,
  established_year: 2019,
  specialties: "Home-style Litti, Tilkut, Sattu Paratha, Kheer"
},
{
  business_name: "Muzaffarpur Litchi Sweets",
  owner_name: "Raman Kumar",
  description: "Famous for our litchi-flavored sweets and traditional Bihar delicacies. We combine the sweetness of Muzaffarpur litchis with age-old recipes to create unique flavors.",
  address: "Litchi Market, Main Road",
  city: "Muzaffarpur",
  state: "Bihar",
  email: "raman@litchisweets.com",
  phone: "+91-9876543215",
  profile_image: "",
  banner_image: "",
  rating: 4.4,
  total_reviews: 92,
  is_verified: false,
  established_year: 2017,
  specialties: "Litchi Sweets, Khaja, Tilkut, Makhana Kheer"
}];